---
pdfdir: /opt/poddisplay/pdf
texdir: /opt/poddisplay/tex
poddir: /opt/poddisplay/pod
packages:
 - makeidx
 - multirow
 - multicol
 - url
 - hyperref
 - bookmark
 - nameref
 - ifthen
 - graphicx
 - verbatim
 - geometry
 - my
 - authblk
 - soul
 - csquotes
 - longtable
 - alltt
 - hypcap
 - textcomp
 - fancyhdr
 - color
 - listings
packopts:
 hyperref : 
     - hyperindex 
     - letterpaper 
     - linktocpage 
     - pdfpagelabels 
     - plainpages=false 
     - bookmarksdepth=subparagraph
 geometry : 
     - hmargin={3cm,1.5cm}
     - vmargin={2cm,2cm}
     - centering
 bookmark : 
     - depth=4
 hypcap : 
     - figure,table
 color : 
     - usenames,dvipsnames
lstset:
     - language=Perl                 
     - backgroundcolor=\color{YellowOrange}
     - escapeinside={(*@}{@*)}
# the size of the fonts that are used for the code
     - basicstyle=\normalfont\ttfamily\small
# where to put the line-numbers
     - numbers=left                  
# the style that is used for the line-numbers
     - numberstyle=\small\color{gray}  
# the step between two line-numbers. If it's 1, each line will be numbered
     - stepnumber=2
# how far the line-numbers are from the code
     - numbersep=5pt
# show spaces adding particular underscores
     - showspaces=false              
# underline spaces within strings
     - showstringspaces=false
#show tabs within strings adding particular underscores
     - showtabs=false                 
#% adds a frame around the code
     - frame=single                   
# if not set, the frame-color may be changed on line-breaks within not-black text (e.g. commens (green here))
     - rulecolor=\color{black}
# sets default tabsize to 2 spaces
     - tabsize=2
# sets the caption-position to bottom
     - captionpos=b
# sets automatic line breaking
     - breaklines=true                
# sets if automatic breaks should only happen at whitespace
     - breakatwhitespace=false        
# show the filename of files included with \lstinputlisting;
# also try caption instead of title
     - title=\lstname                   
# keyword style
     - keywordstyle=\color{Red}         
# comment style
     - commentstyle=\color{Blue}       
#string literal style
     - stringstyle=\color{mauve}         
     - escapeinside={\%*}{*)}            
# if you want to add a comment within your code
#morekeywords={*,...}               % if you want to add more keywords to the set
hypersetup:
     - bookmarksnumbered
     - hyperfigures=true
     - bookmarksdepth=paragraph
     - pdfstartview={FitH}
     - citecolor={blue}
     - linkcolor={red}
     - urlcolor={black}
     - pdfpagemode={UseOutlines}
     - plainpages=false
     - hyperindex=false
