---
abstract: 'Generate perl tags for vim'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Vim-Tag
provides:
  Vim::Tag:
    file: lib/Vim/Tag.pm
    version: 1.110690
  Vim::Tag::Null:
    file: lib/Vim/Tag/Null.pm
    version: 1.110690
requires:
  Class::Accessor::Constructor: 0
  File::Find: 0
  File::Slurp: 0
  Getopt::Inherited: 0
  Hash::Rename: 0
  UNIVERSAL::require: 0
  constant: 0
  parent: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Vim-Tag
  homepage: http://search.cpan.org/dist/Vim-Tag/
  repository: git://github.com/hanekomu/Vim-Tag.git
version: 1.110690
