---
abstract: 'Arrays, hashes, booleans, integers, sets and more'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-Complex
provides:
  Class::Accessor::Complex:
    file: lib/Class/Accessor/Complex.pm
    version: 1.100880
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Accessor::Installer: 0
  Data::Miscellany: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  List::MoreUtils: 0
  Scalar::Util: 0
  Test::More: 0.88
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Class-Accessor-Complex
  homepage: http://search.cpan.org/dist/Class-Accessor-Complex/
  repository: http://github.com/hanekomu/Class-Accessor-Complex
version: 1.100880
