#!/usr/bin/env perl

use warnings;
use strict;

use OP::TEX::PERLTEX;
use FindBin;
use File::Spec;

my %opts=(
	scriptname  => "$FindBin::Script",
	workdir  	=> File::Spec->curdir()
);

my $t=OP::TEX::PERLTEX->new(%opts);

$t->main(@ARGV);
