---
abstract: 'Generate auto completion information for vim'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Vim-Complete
provides:
  Vim::Complete:
    file: lib/Vim/Complete.pm
    version: 1.100880
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  English: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  Getopt::Attribute: 0
  PPI: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::More: 0.88
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Vim-Complete
  homepage: http://search.cpan.org/dist/Vim-Complete/
  repository: http://github.com/hanekomu/Vim-Complete
version: 1.100880
